### ISSUE TITLE
Query expansion notebook is under broken link

### ISSUE THREAD

**Issue by sadaisystems** [deepset-ai/haystack-cookbook#116]
The link looks like this https://colab.research.google.com/github/deepset-ai/haystack-cookbook/blob/main/notebooks/querey-expansion.ipynb.

However, it seems like i typo, when corrected to https://colab.research.google.com/github/deepset-ai/haystack-cookbook/blob/main/notebooks/query-expansion.ipynb, it works just fine.

**Comment by bilgeyucel** [comment]
Thanks for reporting @sadaisystems, I believe this issue is fixed with #117
