### ISSUE TITLE
Cookbook for UpTrain

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-cookbook#51]
Create an cookbook showcasing the new UpTrqain integration. The cookbook should evaluate a RAG pipeline with various metrics:
[UpTrainEvaluator Docs](https://docs.haystack.deepset.ai/v2.0/docs/uptrainevaluator)

**Comment by AnushreeBannadabhavi** [comment]
I'd like to work on this. Will create a PR for review

**Comment by AnushreeBannadabhavi** [comment]
I'd like to work on this. Will create a PR for review

**Comment by anakin87** [comment]
done in #72
