### ISSUE TITLE
Cookbook for DeepEval

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-cookbook#53]
Create an cookbook showcasing the new DeepEval integration. The cookbook should evaluate a RAG pipeline with various metrics:
[DeepEval Docs](https://docs.haystack.deepset.ai/v2.0/docs/deepevalevaluator)

**Comment by srini047** [comment]
@TuanaCelik I would like to take up this issue. I am working on Haystack and am looking to get familiar. So this issue will be a good kickstart.
