### ISSUE TITLE
chroma-indexing-and-rag-examples.ipynb

### ISSUE THREAD

**Issue by silvacarl2** [deepset-ai/haystack-cookbook#64]
when running, after this:

query = "Should I write documentation for my plugin?"
results = querying.run({"retriever": {"queries": [query], "top_k": 3},
                        "prompt_builder": {"query": query},
                        "llm":{"generation_kwargs": {"max_new_tokens": 350}}})

got this:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-6-4ea0ef57d9fa>](https://localhost:8080/#) in <cell line: 2>()
      1 query = "Should I write documentation for my plugin?"
----> 2 results = querying.run({"retriever": {"queries": [query], "top_k": 3},
      3                         "prompt_builder": {"query": query},
      4                         "llm":{"generation_kwargs": {"max_new_tokens": 350}}})

1 frames
[/usr/local/lib/python3.10/dist-packages/haystack/core/pipeline/pipeline.py](https://localhost:8080/#) in _validate_input(self, data)
    602             for socket_name, socket in instance.__haystack_input__._sockets_dict.items():
    603                 if socket.senders == [] and socket.is_mandatory and socket_name not in component_inputs:
--> 604                     raise ValueError(f"Missing input for component {component_name}: {socket_name}")
    605             for input_name in component_inputs.keys():
    606                 if input_name not in instance.__haystack_input__._sockets_dict:

ValueError: Missing input for component retriever: query

**Comment by kuzcotopiallm** [comment]
Try it like this:
```python
results = querying.run({
    "retriever": {"query": query, "top_k": 3},
    "prompt_builder": {"query": query},
    "llm":{"generation_kwargs": {"max_tokens": 350}}
})
```

**Comment by silvacarl2** [comment]
cool will do
