### ISSUE TITLE
multilingual_rag_podcast.ipynb

### ISSUE THREAD

**Issue by silvacarl2** [deepset-ai/haystack-cookbook#65]
this:

transcription = whisper.run(audio_files="/content/podcast.mp3")

returns this error:

TypeError: LocalWhisperTranscriber.run() got an unexpected keyword argument 'audio_files'

**Comment by anakin87** [comment]
It should be:
`transcription = whisper.run(sources="/content/podcast.mp3")`

I opened a PR to fix the notebook.
