### ISSUE TITLE
Create Chat + RAG cookbook with new memory abstractions

### ISSUE THREAD

**Issue by mrm1001** [deepset-ai/haystack-cookbook#97]
Change the existing colab to add new memory abstractions and turn into a cookbook (https://github.com/deepset-ai/haystack/issues/7868).

This is dependent on the memory abstractions being finished:
* https://github.com/deepset-ai/haystack/issues/7917
* https://github.com/deepset-ai/haystack/issues/7918
* https://github.com/deepset-ai/haystack/issues/7919

**Comment by vblagoje** [comment]
@bilgeyucel and @TuanaCelik I would simply add this notebook to [cookbook](https://colab.research.google.com/drive/1XmnvPa8ioiZ_pQaxhJYOaughXajWGeNL?usp=sharing) Is there anything else I need to do, make it really nice etc?

**Comment by bilgeyucel** [comment]
@vblagoje if you can open the PR, I can take it from there :) Thanks 🙏
